### ISSUE TITLE
！！！！TypeError: spawn is not a function

### ISSUE THREAD

**Issue by spcBackToLife** [TooTallNate/node-applescript#16]
![image](https://user-images.githubusercontent.com/20703494/42802310-21a0d8a8-89d5-11e8-93c9-9af2f52fd768.png)

**Comment by sonicdoe** [comment]
Could you elaborate a bit? How are you calling this package? Which tool is rendering this error message?

**Comment by spcBackToLife** [comment]
thanks for your reply, i run on the wrong place.(react environment). it is ok when  run on  node environment.
